### ISSUE TITLE
Repeated files

### ISSUE THREAD

**Issue by alisonmonteiro** [adrianosferreira/rio2016#1]
Hi,

[`rio2016.js`](https://github.com/adrianosferreira/rio2016/blob/master/rio2016.js) and [`lib/calendar.js`](https://github.com/adrianosferreira/rio2016/blob/master/lib/calendar.js) are the same file.
What does that mean?

**Comment by adrianosferreira** [comment]
The calendar.js is a not needed file, used only in dev. I've removed it and will publish a new version of the NPM package. Thanks!
